networks:
  internal:
    driver: bridge
    name: internal
  external:
    external: true
    name: external

services:
  akaunting.php:
    build: .docker/php
    volumes:
      - ./volumes/akaunting:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm/
    restart: unless-stopped
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - AKAUNTING_VERSION=${AKAUNTING_VERSION:-3.1.11}
      - ADM_EMAIL=${ADM_EMAIL:-admin@test.domain}
      - ADM_PASSWD=${ADM_PASSWD:-admin}

      - APP_ENV=${APP_ENV:-local}

      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_DATABASE=${DB_DATABASE:-akaunting}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - DB_PREFIX=${DB_PREFIX:-}

      - MAIL_HOST=${MAIL_HOST:-mailpit}
      - MAIL_PORT=${MAIL_PORT:-1025}

      - OPENBAO_ADDR=${OPENBAO_ADDR:-http://openbao:8200}
      - OPENBAO_TOKEN=${OPENBAO_TOKEN:-dev-only-root-token}

      - XDEBUG_CONFIG
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - internal
  akaunting.nginx:
    build:
      context: .docker/nginx
      args:
        NGINX_CONF: http
    restart: unless-stopped
    volumes:
      - ./volumes/akaunting:/var/www/html:ro
    depends_on:
      - akaunting.php
    ports:
      - 8082:80
    networks:
      - internal
      - external
  akaunting.mysql:
    image: mysql
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-akaunting}
    networks:
      - internal
      - external
