name: Bats

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Bats
        uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 # 4.0.0
        with:
          support-install: false
          assert-install: false
          detik-install: false
          file-install: false

      - name: Run Bats
        run: bats tests/*.bats
